services:
  - type: web
    name: ornament-backend
    env: python
    plan: free
    rootDir: backend
    runtime: python-3.11.8
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000 --workers 1
